"""
JURA WiFi Connect V2 — Direct TCP 51515 Protocol Client

Communicates directly with the WiFi Connect V2 dongle using the
reverse-engineered encrypted protocol (decompiled from J.O.E. APK).

The dongle proxies commands to the JURA E4 machine over serial,
handling all machine-level encryption internally.
"""

import random
import socket
import threading
import time
import logging
from dataclasses import dataclass
from typing import Optional, List

from PyQt5.QtCore import QObject, pyqtSignal

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEFAULT_DONGLE_IP = "192.168.1.105"
DONGLE_PORT = 51515
TCP_TIMEOUT = 5
RECV_BUF = 4096

# Auth hash from J.O.E. app — generated by SecurityManager.getHash(uniqueName)
# during initial pairing in WifiCommandConnectionSetup.java.  The hash is
# per-dongle and stored on the phone.  Once captured (e.g. from a PCAP or
# the app's shared prefs), it is static and reusable indefinitely.
# @HP format: @HP:<PIN>,<DEVICE_NAME_HEX>,<AUTH_HASH>
# Responses: @hp4 = OK, @hp5:00 = wrong PIN, @hp5:01 = wrong hash
AUTH_HASH = ""  # Set your dongle's auth hash here (captured from J.O.E. app)
DEVICE_NAME = "JURA-Desktop"

BREW_COOLDOWN_SECONDS = 10
STATUS_POLL_INTERVAL = 4
HEARTBEAT_INTERVAL = 9

# E4 product code → @TP parameter template (16 bytes as hex)
# Byte layout: [product, 0, strength, volume_units, 0, 0, temp, 0, 01, 0...0, grinder_flag]
E4_PRODUCTS_V2 = {
    0x02: "espresso",
    0x03: "coffee",
    0x0D: "hotwater",
}

# ---------------------------------------------------------------------------
# WiFi V2 Encryption (from J.O.E. APK: WifiCryptoUtil.java)
# ---------------------------------------------------------------------------

_DISC_ONE = [1, 0, 3, 2, 15, 14, 8, 10, 6, 13, 7, 12, 11, 9, 5, 4]
_DISC_TWO = [9, 12, 6, 11, 10, 15, 2, 14, 13, 0, 4, 3, 1, 8, 7, 5]
_ESC_CHARS = frozenset({0, 10, 13, 38, 27})


def _norm(v: int) -> int:
    return v % 256


def _half_byte(data: int, turn: int, k1: int, k2: int) -> int:
    idx1 = _norm(data + turn + k1) % 16
    t = turn >> 4
    val1 = _DISC_ONE[idx1]
    idx2 = _norm(val1 + k2 + _norm(t) - turn - k1) % 16
    val2 = _DISC_TWO[idx2]
    idx3 = _norm(val2 + k1 + turn - k2 - _norm(t)) % 16
    val3 = _DISC_ONE[idx3]
    return _norm(_norm(val3 - turn - k1) % 16)


def _gen_key() -> int:
    rng = random.Random(int(time.time() * 1000))
    while True:
        k = rng.randint(0, 255)
        if (k & 0x0F) not in (14, 15):
            return k


def encrypt(plaintext: str) -> bytes:
    """Encrypt a command string into a wire-format message."""
    key = _gen_key()
    k1 = (key >> 4) & 0x0F
    k2 = key & 0x0F
    out = bytearray()
    if key in _ESC_CHARS:
        out.append(0x1b)
        out.append(key ^ 0x80)
    else:
        out.append(key)
    turn = 0
    for b in plaintext.encode("utf-8"):
        hi = _half_byte((b >> 4) & 0x0F, turn, k1, k2)
        turn += 1
        lo = _half_byte(b & 0x0F, turn, k1, k2)
        turn += 1
        enc = _norm((hi << 4) | _norm(lo))
        if enc in _ESC_CHARS:
            out.append(0x1b)
            enc ^= 0x80
        out.append(_norm(enc))
    return bytes([0x2a]) + bytes(out) + b"\r\n"


def decrypt(raw: bytes) -> str:
    """Decrypt a wire-format message to plaintext string."""
    if not raw or raw[0] != 0x2a:
        raise ValueError(f"Bad prefix: {raw[0]:#04x}" if raw else "Empty")
    data = raw[1:]
    if data[-2:] == b"\r\n":
        data = data[:-2]
    pos = 0
    if data[pos] == 0x1b:
        key = data[pos + 1] ^ 0x80
        pos = 2
    else:
        key = data[pos]
        pos = 1
    k1 = (key >> 4) & 0x0F
    k2 = key & 0x0F
    result = bytearray()
    turn = 0
    while pos < len(data):
        b = data[pos]
        if b == 0x1b:
            pos += 1
            b = data[pos] ^ 0x80
        hi = _half_byte((b >> 4) & 0x0F, turn, k1, k2)
        turn += 1
        lo = _half_byte(b & 0x0F, turn, k1, k2)
        turn += 1
        result.append((hi << 4) | lo)
        pos += 1
    return result.decode("utf-8", errors="replace")


# ---------------------------------------------------------------------------
# Data Types
# ---------------------------------------------------------------------------

@dataclass
class WiFiV2DeviceInfo:
    ip: str
    port: int
    name: str
    firmware: str
    machine_type: str
    mac: str


@dataclass
class MachineStatistics:
    """Machine statistics and maintenance data."""
    # Product counters (lifetime totals)
    total_products: int = 0
    espresso_count: int = 0
    coffee_count: int = 0
    hotwater_count: int = 0
    # Maintenance percentages (0-100, -1 = not applicable)
    cleaning_pct: int = -1
    descaling_pct: int = -1
    filter_pct: int = -1
    # Maintenance cycle counts
    cleaning_count: int = 0
    descaling_count: int = 0
    filter_count: int = 0


# ---------------------------------------------------------------------------
# WiFi V2 Manager
# ---------------------------------------------------------------------------

class WiFiV2Manager(QObject):
    """Manages TCP 51515 communication with the JURA WiFi Connect V2 dongle.

    Same signal interface as WiFiManager / BLEManager so the GUI can use
    any connection type transparently.
    """

    scan_finished    = pyqtSignal(list)
    connect_ok       = pyqtSignal(str)
    connect_fail     = pyqtSignal(str)
    disconnected     = pyqtSignal()
    status_update    = pyqtSignal(list)
    brew_started     = pyqtSignal()
    brew_progress    = pyqtSignal(int, int)   # (percent 0-100, temperature_celsius)
    brew_error       = pyqtSignal(str)
    error            = pyqtSignal(str)
    statistics_ready = pyqtSignal(object)     # MachineStatistics

    def __init__(self):
        super().__init__()
        self._lock = threading.Lock()
        self._sock_lock = threading.Lock()  # guards socket send/recv pairs
        self._connected = False
        self._brewing = False
        self._last_brew_time = 0.0
        self._sock: Optional[socket.socket] = None
        self._stop_event = threading.Event()
        self._recv_thread: Optional[threading.Thread] = None
        self._poll_thread: Optional[threading.Thread] = None
        self._dongle_ip: Optional[str] = None

    # -- Thread-safe properties --

    @property
    def is_connected(self):
        with self._lock:
            return self._connected

    @property
    def is_brewing(self):
        with self._lock:
            return self._brewing

    def _set_connected(self, value: bool):
        with self._lock:
            self._connected = value
            if not value:
                self._brewing = False

    def _set_brewing(self, value: bool):
        with self._lock:
            self._brewing = value

    # -- Socket helpers --

    def _send(self, cmd: str) -> bool:
        """Send an encrypted command. Returns True on success."""
        try:
            if self._sock is None:
                return False
            msg = encrypt(cmd + "\r\n")
            self._sock.sendall(msg)
            logger.debug("V2 TX: %s", cmd)
            return True
        except (OSError, socket.error) as e:
            logger.warning("V2 send failed: %s", e)
            return False

    def _recv_all(self, timeout: float = 2.0) -> List[str]:
        """Receive and decrypt all pending messages."""
        messages = []
        if self._sock is None:
            return messages
        self._sock.settimeout(timeout)
        buf = b""
        try:
            while True:
                chunk = self._sock.recv(RECV_BUF)
                if not chunk:
                    break
                buf += chunk
                while b"\r\n" in buf:
                    idx = buf.index(b"\r\n")
                    raw_msg = buf[:idx + 2]
                    buf = buf[idx + 2:]
                    try:
                        plain = decrypt(raw_msg).rstrip("\r\n")
                        messages.append(plain)
                        logger.debug("V2 RX: %s", plain)
                    except Exception as e:
                        logger.warning("V2 decrypt error: %s", e)
                self._sock.settimeout(0.3)
        except socket.timeout:
            pass
        except (OSError, socket.error):
            pass
        return messages

    # -- UDP Discovery --

    @staticmethod
    def _udp_discover(timeout: float = 3.0) -> List[WiFiV2DeviceInfo]:
        """Send UDP discovery probe and collect V2 dongle responses.

        Uses direct unicast to known IP (works across subnets) plus
        broadcast on the local network.
        """
        results = []
        probe = bytes.fromhex("0010a5f3") + b"\x00" * 12

        # Probe known IPs via unicast (works across routed subnets)
        probe_targets = [DEFAULT_DONGLE_IP]

        for target_ip in probe_targets:
            try:
                s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
                s.settimeout(timeout)
                s.sendto(probe, (target_ip, DONGLE_PORT))
                data, addr = s.recvfrom(256)
                s.close()
                if len(data) >= 117 and data[2:4] == b"\xa5\xf3":
                    firmware = data[4:20].split(b"\x00")[0].decode("ascii", errors="replace")
                    ssid = data[20:52].split(b"\x00")[0].decode("ascii", errors="replace")
                    machine = data[52:68].split(b"\x00")[0].decode("ascii", errors="replace")
                    mac_bytes = data[104:110]
                    mac = ":".join(f"{b:02x}" for b in mac_bytes)
                    results.append(WiFiV2DeviceInfo(
                        ip=addr[0],
                        port=DONGLE_PORT,
                        name=ssid or "WiFi Connect V2",
                        firmware=firmware,
                        machine_type=machine,
                        mac=mac,
                    ))
            except socket.timeout:
                pass
            except Exception as e:
                logger.debug("V2 UDP probe to %s failed: %s", target_ip, e)

        return results

    # -- Public API --

    def scan(self):
        threading.Thread(target=self._do_scan, daemon=True).start()

    def connect_machine(self, ip: str, port: int = DONGLE_PORT):
        threading.Thread(target=self._do_connect, args=(ip,), daemon=True).start()

    def disconnect_machine(self):
        self._do_disconnect()

    def brew(self, product_code, strength, volume_ml, volume_step, temperature):
        with self._lock:
            if self._brewing:
                self.brew_error.emit("A brew is already in progress")
                return
            now = time.monotonic()
            if now - self._last_brew_time < BREW_COOLDOWN_SECONDS:
                remaining = int(BREW_COOLDOWN_SECONDS - (now - self._last_brew_time))
                self.brew_error.emit(f"Please wait {remaining}s between brews")
                return
        threading.Thread(
            target=self._do_brew,
            args=(product_code, strength, volume_ml, volume_step, temperature),
            daemon=True,
        ).start()

    def _send_recv(self, cmd: str, timeout: float = 2.0) -> List[str]:
        """Thread-safe send command and receive responses."""
        with self._sock_lock:
            if self._send(cmd):
                return self._recv_all(timeout=timeout)
        return []

    def send_command(self, cmd: str) -> Optional[str]:
        """Send a raw @ command. Returns first response or None."""
        if not self._connected or self._sock is None:
            return None
        resps = self._send_recv(cmd)
        return resps[0] if resps else None

    def disconnect_and_wait(self, timeout=3):
        self._do_disconnect()

    def shutdown(self):
        self._do_disconnect()

    # ======================================================================
    # Discovery
    # ======================================================================

    def _do_scan(self):
        try:
            gui_results = []

            # Try UDP discovery first
            results = self._udp_discover(timeout=3)
            for d in results:
                gui_results.append(WiFiV2DeviceInfo(
                    ip=d.ip,
                    port=d.port,
                    name=d.name or "WiFi Connect V2",
                    firmware=d.firmware,
                    machine_type=d.machine_type,
                    mac=d.mac,
                ))

            # If UDP found nothing, offer default dongle IP
            # (UDP discovery may not work across routed subnets; TCP
            # probe is avoided because the dongle has a single-connection
            # limit and the probe would block the subsequent real connect)
            if not gui_results:
                logger.info("V2 scan: UDP found nothing, offering default IP")
                gui_results.append(WiFiV2DeviceInfo(
                    ip=DEFAULT_DONGLE_IP,
                    port=DONGLE_PORT,
                    name="WiFi Connect V2",
                    firmware="TT237W",
                    machine_type="JURA E4",
                    mac="",
                ))

            logger.info("V2 scan: found %d device(s)", len(gui_results))
            self.scan_finished.emit(gui_results)
        except Exception as e:
            logger.exception("V2 scan failed")
            self.error.emit(f"Scan failed: {e}")
            self.scan_finished.emit([])

    # ======================================================================
    # Connection
    # ======================================================================

    def _do_connect(self, ip: str):
        try:
            self._dongle_ip = ip
            logger.info("V2 connect: %s:%d", ip, DONGLE_PORT)

            # TCP connect
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(TCP_TIMEOUT)
            sock.connect((ip, DONGLE_PORT))
            self._sock = sock

            # Authenticate
            name_hex = DEVICE_NAME.encode("ascii").hex().upper()
            hp_cmd = f"@HP:,{name_hex},{AUTH_HASH}"
            if not self._send(hp_cmd):
                self._close_socket()
                self.connect_fail.emit("Failed to send authentication")
                return

            resps = self._recv_all(timeout=3)
            hp_ok = any(r.startswith("@hp") for r in resps)
            if not hp_ok:
                self._close_socket()
                self.connect_fail.emit(
                    f"Authentication rejected by dongle at {ip}\n"
                    "The auth hash may need to be re-captured from J.O.E."
                )
                return

            # Start session
            self._send("@TS:01")
            self._recv_all(timeout=1)

            # Read machine type for display
            self._send("@TG:C0")
            tg_resps = self._recv_all(timeout=2)

            self._set_connected(True)
            self._stop_event.clear()

            # Start background threads
            self._poll_thread = threading.Thread(target=self._status_loop, daemon=True)
            self._poll_thread.start()

            # Show machine name (we know it's an E4 from the dongle)
            display = f"JURA E4 — WiFi V2 ({ip})"
            self.connect_ok.emit(display)
            logger.info("V2 connected: %s", display)

        except socket.timeout:
            self._close_socket()
            self.connect_fail.emit(
                f"Connection timeout to {ip}:{DONGLE_PORT}\n"
                "Check that the machine is powered on."
            )
        except ConnectionRefusedError:
            self._close_socket()
            self.connect_fail.emit(
                "Connection refused by the dongle.\n"
                "If J.O.E. is open on your phone, close it first\n"
                "\u2014 the dongle only accepts one connection at a time."
            )
        except Exception as e:
            logger.exception("V2 connect failed")
            self._close_socket()
            self.connect_fail.emit(str(e))

    def _close_socket(self):
        try:
            if self._sock:
                self._sock.close()
        except Exception:
            pass
        self._sock = None

    def _do_disconnect(self):
        with self._lock:
            was_connected = self._connected
            self._connected = False
            self._brewing = False
        self._stop_event.set()

        # Send session close
        if self._sock:
            try:
                self._send("@TS:00")
                time.sleep(0.2)
            except Exception:
                pass
        self._close_socket()
        if was_connected:
            self.disconnected.emit()

    # ======================================================================
    # Status polling
    # ======================================================================

    def _status_loop(self):
        fail_count = 0
        while not self._stop_event.is_set():
            with self._lock:
                if not self._connected:
                    return
                if self._brewing:
                    self._stop_event.wait(1)
                    continue

            try:
                resps = self._send_recv("@TG:C0")
                if resps:
                    status_parsed = False
                    for r in resps:
                        if r.startswith("@TF:") or r.startswith("@tf:"):
                            # Full status bitmask (same as BLE MACHINE_STATUS)
                            alerts = self._parse_tf_bitmask(r[4:])
                            if alerts is not None:
                                self.status_update.emit(alerts)
                                status_parsed = True
                        elif r.startswith("@tg:C0"):
                            if not status_parsed:
                                alerts = self._parse_status_v2(r[4:])
                                self.status_update.emit(alerts)
                                status_parsed = True
                    if status_parsed:
                        fail_count = 0
                    else:
                        fail_count += 1
                else:
                    fail_count += 1

                if fail_count >= 5:
                    logger.warning("V2 status: %d failures, disconnecting", fail_count)
                    self._do_disconnect()
                    return

            except Exception:
                fail_count += 1

            self._stop_event.wait(STATUS_POLL_INTERVAL)

    @staticmethod
    def _parse_tf_bitmask(hex_data: str):
        """Parse @TF: response — full BLE-style alert bitmask.

        Same bit layout as jura_protocol.ALERTS.  Returns alert list or None
        if the data is too short / unparseable.
        """
        from jura_protocol import ALERTS
        try:
            if len(hex_data) < 4:
                return None
            raw = bytes.fromhex(hex_data)
            alerts = []
            for i in range(len(raw) * 8):
                byte_off = i >> 3
                bit_off = 7 - (i & 0b111)
                if byte_off < len(raw) and (raw[byte_off] >> bit_off) & 1:
                    name, severity = ALERTS.get(i, (f"Alert #{i}", "info"))
                    alerts.append((i, name, severity))
            return alerts if alerts else [(13, "Coffee ready", "success")]
        except (ValueError, IndexError):
            return None

    @staticmethod
    def _parse_status_v2(hex_data: str) -> list:
        """Parse @tg:C0 response as fallback when no @TF is available.

        3 bytes after C0: Cleaning %, Filter %, Descaling %.
        Also surfaces maintenance warnings when percentages are low.
        """
        alerts = []
        try:
            if len(hex_data) >= 4:
                status_bytes = bytes.fromhex(hex_data)
                state_byte = status_bytes[1] if len(status_bytes) > 1 else 0
                if state_byte == 0x64:
                    alerts.append((13, "Coffee ready", "success"))
                elif state_byte == 0x00:
                    alerts.append((12, "Heating up", "info"))
                else:
                    alerts.append((17, "Please wait", "info"))
                # Surface maintenance warnings from the same response
                if len(status_bytes) >= 4:
                    names = ["Cleaning", "Filter", "Descaling"]
                    for i, name in enumerate(names):
                        pct = status_bytes[i + 1]
                        if pct != 255 and pct <= 15:
                            alerts.append((33 + i, f"{name} due", "warning"))
        except (ValueError, IndexError):
            alerts = [(13, "Coffee ready", "success")]
        return alerts

    def _handle_brew_progress(self, tv_msg: str):
        """Handle @TV: brew progress push messages."""
        try:
            hex_data = tv_msg[4:]
            if len(hex_data) >= 4:
                # Short @TV (4 chars like "3E02") = brew complete
                if len(hex_data) <= 4:
                    logger.info("V2: brew complete signal")
                    self._set_brewing(False)
                    return
                # Long @TV: byte at offset 11 (hex chars 22-23) is progress 0-100
                if len(hex_data) >= 24:
                    progress_byte = int(hex_data[22:24], 16)
                    logger.debug("V2: brew progress %d%%", progress_byte)
                    if progress_byte >= 100:
                        self._set_brewing(False)
        except Exception:
            pass

    # ======================================================================
    # Statistics & Maintenance
    # ======================================================================

    def read_statistics(self):
        """Read all statistics from the machine. Emits statistics_ready."""
        if self._brewing:
            return
        threading.Thread(target=self._do_read_statistics, daemon=True).start()

    def _do_read_statistics(self):
        if not self._connected or self._sock is None:
            return

        stats = MachineStatistics()

        # 1. Maintenance percentages (@TG:C0)
        #    3 bytes: Cleaning %, Filter %, Descaling % (255 = N/A)
        for r in self._send_recv("@TG:C0"):
            if r.startswith("@tg:C0") and len(r) >= 12:
                try:
                    b = bytes.fromhex(r[6:12])
                    stats.cleaning_pct = b[0] if b[0] != 255 else -1
                    stats.filter_pct = b[1] if b[1] != 255 else -1
                    stats.descaling_pct = b[2] if b[2] != 255 else -1
                except (ValueError, IndexError):
                    pass
                break

        # 2. Maintenance counters (@TG:43)
        #    2 bytes each: Cleaning, Filter, Descaling, ...
        for r in self._send_recv("@TG:43"):
            if r.startswith("@tg:43"):
                hex_data = r[6:]
                try:
                    if len(hex_data) >= 4:
                        stats.cleaning_count = int(hex_data[0:4], 16)
                    if len(hex_data) >= 8:
                        stats.filter_count = int(hex_data[4:8], 16)
                    if len(hex_data) >= 12:
                        stats.descaling_count = int(hex_data[8:12], 16)
                except ValueError:
                    pass
                break

        # 3. Product counters (@TR:32,00) — page 0
        #    Contains: Total (pos 0), pos 1, Espresso (pos 2), Coffee (pos 3)
        self._read_product_page("00", 0, stats)

        # 4. Product counters (@TR:32,03) — page 3
        #    Contains: pos 12, Hot Water (pos 13 = 0x0D), pos 14, pos 15
        self._read_product_page("03", 3, stats)

        logger.info(
            "V2 statistics: total=%d espresso=%d coffee=%d hotwater=%d "
            "clean=%d%% descale=%d%% filter=%d%%",
            stats.total_products, stats.espresso_count, stats.coffee_count,
            stats.hotwater_count, stats.cleaning_pct, stats.descaling_pct,
            stats.filter_pct,
        )
        self.statistics_ready.emit(stats)

    def _read_product_page(self, page_hex: str, page_num: int, stats):
        """Read one page of product counter register @TR:32.

        WiFi V2 response format: @tr:32,XX,<16 hex chars>
        16 chars = 4 products * 2 bytes (uint16).  No page counter byte.
        0xFFFF = product does not exist on this machine.
        """
        cmd = f"@TR:32,{page_hex}"
        for r in self._send_recv(cmd, timeout=3):
            r_lower = r.lower()
            if not (r_lower.startswith(f"@tr:32,{page_hex}") or r_lower.startswith("@tr:00")):
                continue  # skip unsolicited messages (e.g. @TF push)
            # Data follows the last comma
            parts = r.split(",")
            hex_data = parts[-1] if len(parts) >= 3 else ""
            # 4 products per page, 4 hex chars (uint16) each — no page counter
            for pos in range(4):
                off = pos * 4
                if off + 4 > len(hex_data):
                    break
                try:
                    val = int(hex_data[off:off + 4], 16)
                except ValueError:
                    continue
                if val == 0xFFFF:
                    continue
                flat = page_num * 4 + pos
                if flat == 0:
                    stats.total_products = val
                elif flat == 2:   # Espresso (0x02)
                    stats.espresso_count = val
                elif flat == 3:   # Coffee (0x03)
                    stats.coffee_count = val
                elif flat == 13:  # Hot Water (0x0D)
                    stats.hotwater_count = val
            break

    # ======================================================================
    # Brewing
    # ======================================================================

    def _do_brew(self, product_code, strength, volume_ml, volume_step, temperature):
        if not self._connected or self._sock is None:
            self.brew_error.emit("Not connected")
            return

        if product_code not in E4_PRODUCTS_V2:
            self.brew_error.emit(f"Unknown product code: {product_code:#04x}")
            return

        try:
            self._set_brewing(True)
            with self._lock:
                self._last_brew_time = time.monotonic()

            # Build @TP parameter (16 bytes = 32 hex chars)
            params = bytearray(16)
            params[0] = product_code & 0xFF
            params[2] = max(1, min(strength, 3)) if product_code != 0x0D else 0
            params[3] = max(1, volume_ml // max(volume_step, 1))
            params[6] = max(0, min(temperature, 2))
            params[8] = 0x01  # start flag (always required)
            params[15] = 0x04  # grinder instructions flag

            tp_hex = params.hex().upper()
            logger.info(
                "V2 brew: %s (@TP:%s) strength=%d vol=%dml temp=%d",
                E4_PRODUCTS_V2[product_code], tp_hex,
                strength, volume_ml, temperature,
            )

            if not self._send(f"@TP:{tp_hex}"):
                self._set_brewing(False)
                self.brew_error.emit("Failed to send brew command")
                return

            # Wait for @tp acknowledgment
            resps = self._recv_all(timeout=5)
            tp_ok = any(r.startswith("@tp") for r in resps)
            if not tp_ok:
                self._set_brewing(False)
                self.brew_error.emit("Machine did not acknowledge brew command")
                return

            self.brew_started.emit()
            logger.info("V2 brew: acknowledged, listening for live progress")

            # Listen for @TB/@TV push messages (real-time progress from dongle)
            deadline = time.monotonic() + 120  # 120s safety timeout
            while self._brewing and time.monotonic() < deadline:
                if self._stop_event.is_set():
                    break
                resps = self._recv_all(timeout=2)
                for r in resps:
                    if r.startswith("@TV:"):
                        hex_data = r[4:]
                        if len(hex_data) <= 4:
                            # Short @TV = brew complete
                            logger.info("V2 brew: complete (short @TV)")
                            self.brew_progress.emit(100, 0)
                            self._set_brewing(False)
                            break
                        if len(hex_data) >= 30:
                            # Full @TV: byte 14 = progress, byte 0 = temperature
                            try:
                                pct = int(hex_data[28:30], 16)
                                temp_c = int(hex_data[0:2], 16)
                                logger.debug("V2 brew: %d%% temp=%d°C", pct, temp_c)
                                self.brew_progress.emit(min(pct, 100), temp_c)
                                if pct >= 100:
                                    self._set_brewing(False)
                                    break
                            except ValueError:
                                pass
                    elif r.startswith("@TB"):
                        logger.info("V2 brew: begin signal")

            self._set_brewing(False)

        except Exception as e:
            self._set_brewing(False)
            self.brew_error.emit(str(e))
